[package]
name = "mclang"
version = "0.1.0"
authors = ["seunomonije <seunomonije@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.2"
ndarray-linalg = "0.13.1"
